Console.WriteLine("Введите первое число");
int x = Convert.ToInt32(Console.ReadLine());
Console.WriteLine("Введите второе число");
int y = Convert.ToInt32(Console.ReadLine());
Console.WriteLine("Введите третье число");
int z = Convert.ToInt32(Console.ReadLine());
int Max = x;
if (y > Max) Max = y;
if (z > Max) Max = z;
Console.WriteLine(Max);
